site_name: PHP DomTemplate
site_url: https://domtemplate.tropotek.com/
repo_url: https://github.com/tropotek/tk-domtemplate/
site_description: 'PHP DomTemplate, a fast and simple template engine for PHP'
site_author: 'Michael Mifsud <http://www.tropotek.com/>'
copyright: 'Copyright (c) 2008-present Tropotek'
use_directory_urls: false
theme: readthedocs

nav:
  - Home: index.md
  - Dom Template: domTemplate.md
  - Dom Form: domForm.md
  - Dom Renderer: domRenderer.md
  - Dom Parser: domParser.md
  - Dom Modifier: domModifier.md
  - Dom Builder: domBuilder.md
  - Symfony Integration: symfony.md
  - Examples: examples/index.html

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - def_list
  - tables

plugins:
  - search

exclude_docs: |
  *.py
